version: '3.8'
services:
  kuna-database:
    container_name: kuna-database
    image: 'postgres'
    ports:
      # - '1433:5432'
      - '5432:5432'
    volumes:
      - kuna-database-data-postgres:/var/lib/postgresql/data
    networks:
      - espresso

volumes:
  kuna-database-data-postgres:

networks:
  espresso:
